const DOCTRINES = {
  western: {
    id: 'western',
    name: 'Western Doctrine',
    icon: '⚡',
    description: 'High-tech power projection. Superior firepower, air dominance, and expeditionary warfare. Expensive but devastating.',
    bonuses: {
      defenseMultiplier: 1.15,
      attackMultiplier: 1.30,
      economyBonus: 0.25,
      productionSpeed: 0.65,
      unitCostReduction: -0.15,
      diplomacyBonus: 0.15,
      morale: 0.15,
      infantryBonus: 0.30,
      armorBonus: 0.25,
      airBonus: 0.30,
      navalBonus: 0.25,
      techBonus: 0.15,
    },
    specialties: ['Main Battle Tank', 'Attack Helicopter', 'AWACS', 'Expeditionary Force'],
    weakness: 'High resource consumption, slower mass production',
    color: '#bf2d2d',
    units: {
      infantry: 'Armored Infantry',
      tank: 'M1 Abrams',
      aircraft: 'F-35 Lightning',
      helicopter: 'AH-64 Apache',
    },
  },
  european: {
    id: 'european',
    name: 'European Doctrine',
    icon: '🛡️',
    description: 'Balanced combined-arms doctrine. Mechanized warfare, tank destroyers, strike fighters. Cost-effective and diplomatic.',
    bonuses: {
      defenseMultiplier: 1.20,
      attackMultiplier: 1.10,
      economyBonus: 0.15,
      productionSpeed: 0.80,
      unitCostReduction: 0.10,
      diplomacyBonus: 0.25,
      morale: 0.10,
      infantryBonus: 0.20,
      armorBonus: 0.20,
      airBonus: 0.15,
      navalBonus: 0.10,
      techBonus: 0.20,
    },
    specialties: ['Mechanized Infantry', 'Tank Destroyer', 'Eurofighter Typhoon', 'Diplomatic Corps'],
    weakness: 'Lower raw firepower in direct confrontation',
    color: '#2d6abf',
    units: {
      infantry: 'Mechanized Infantry',
      tank: 'Leopard 2',
      aircraft: 'Eurofighter',
      helicopter: 'Tiger HAD',
    },
  },
  eastern: {
    id: 'eastern',
    name: 'Eastern Doctrine',
    icon: '🏗️',
    description: 'Mass production and overwhelming firepower. Cheap units, artillery barrages, SAM coverage. Quantity has a quality of its own.',
    bonuses: {
      defenseMultiplier: 1.10,
      attackMultiplier: 1.20,
      economyBonus: -0.05,
      productionSpeed: 0.90,
      unitCostReduction: 0.30,
      diplomacyBonus: -0.15,
      morale: 0.25,
      infantryBonus: 0.15,
      armorBonus: 0.30,
      airBonus: -0.05,
      navalBonus: -0.15,
      techBonus: -0.10,
    },
    specialties: ['Massed Artillery', 'T-14 Armata', 'S-400 SAM', 'Human Wave'],
    weakness: 'Weak air force and navy, lower technology',
    color: '#6b2dbf',
    units: {
      infantry: 'Motorized Infantry',
      tank: 'T-14 Armata',
      aircraft: 'Su-57 Felon',
      helicopter: 'Mi-28 Havoc',
    },
  },
};

const DOCTRINE_ASSIGNMENTS = {
  germany: 'european',
  france: 'european',
  uk: 'western',
  italy: 'european',
  spain: 'european',
  portugal: 'european',
  netherlands: 'european',
  belgium: 'european',
  switzerland: 'european',
  austria: 'european',
  poland: 'eastern',
  czech: 'european',
  hungary: 'eastern',
  romania: 'eastern',
  greece: 'european',
  bulgaria: 'eastern',
  serbia: 'eastern',
  sweden: 'european',
  norway: 'european',
  finland: 'european',
  denmark: 'european',
  ireland: 'european',
  russia: 'eastern',
  ukraine: 'eastern',
  belarus: 'eastern',
  turkey: 'western',
  lithuania: 'eastern',
  latvia: 'eastern',
  estonia: 'eastern',
  croatia: 'eastern',
  slovakia: 'eastern',
  slovenia: 'european',
  bosnia: 'eastern',
  luxembourg: 'european',
  moldova: 'eastern',
  albania: 'western',
  north_macedonia: 'eastern',
  montenegro: 'eastern',
};

function getDoctrineBonuses(factionId) {
  const doctrineId = DOCTRINE_ASSIGNMENTS[factionId] || 'european';
  const doctrine = DOCTRINES[doctrineId];
  return { doctrineId, doctrine, bonuses: doctrine.bonuses };
}

module.exports = { DOCTRINES, DOCTRINE_ASSIGNMENTS, getDoctrineBonuses };
