const FACTIONS_CONFIG = {
  germany: {
    name: 'Germany',
    flag: '🇩🇪',
    color: '#FF1744',
    personality: {
      aggression: 0.75,
      paranoia: 0.60,
      greed: 0.70,
      honor: 0.40,
      cunning: 0.65,
      bravery: 0.70,
      diplomacy: 0.50,
      expansionism: 0.80,
      nationalism: 0.75,
    },
    military: { army: 350, air: 200, navy: 100, tech: 0.85 },
    economy: 900,
    population: 8300,
  },
  france: {
    name: 'France',
    flag: '🇫🇷',
    color: '#00E5FF',
    personality: {
      aggression: 0.50,
      paranoia: 0.55,
      greed: 0.45,
      honor: 0.70,
      cunning: 0.55,
      bravery: 0.60,
      diplomacy: 0.70,
      expansionism: 0.40,
      nationalism: 0.65,
    },
    military: { army: 300, air: 180, navy: 120, tech: 0.80 },
    economy: 850,
    population: 6700,
  },
  uk: {
    name: 'United Kingdom',
    flag: '🇬🇧',
    color: '#1DE9B6',
    personality: {
      aggression: 0.55,
      paranoia: 0.50,
      greed: 0.55,
      honor: 0.75,
      cunning: 0.70,
      bravery: 0.65,
      diplomacy: 0.75,
      expansionism: 0.45,
      nationalism: 0.60,
    },
    military: { army: 250, air: 220, navy: 200, tech: 0.90 },
    economy: 880,
    population: 6700,
  },
  italy: {
    name: 'Italy',
    flag: '🇮🇹',
    color: '#FF6D00',
    personality: {
      aggression: 0.55,
      paranoia: 0.45,
      greed: 0.50,
      honor: 0.55,
      cunning: 0.60,
      bravery: 0.45,
      diplomacy: 0.65,
      expansionism: 0.60,
      nationalism: 0.55,
    },
    military: { army: 250, air: 150, navy: 130, tech: 0.70 },
    economy: 650,
    population: 6000,
  },
  spain: {
    name: 'Spain',
    flag: '🇪🇸',
    color: '#FF5252',
    personality: {
      aggression: 0.45,
      paranoia: 0.40,
      greed: 0.40,
      honor: 0.65,
      cunning: 0.50,
      bravery: 0.50,
      diplomacy: 0.60,
      expansionism: 0.35,
      nationalism: 0.60,
    },
    military: { army: 200, air: 120, navy: 100, tech: 0.65 },
    economy: 550,
    population: 4700,
  },
  portugal: {
    name: 'Portugal',
    flag: '🇵🇹',
    color: '#69F0AE',
    personality: {
      aggression: 0.30,
      paranoia: 0.35,
      greed: 0.35,
      honor: 0.60,
      cunning: 0.55,
      bravery: 0.40,
      diplomacy: 0.70,
      expansionism: 0.30,
      nationalism: 0.50,
    },
    military: { army: 100, air: 80, navy: 80, tech: 0.60 },
    economy: 350,
    population: 1000,
  },
  netherlands: {
    name: 'Netherlands',
    flag: '🇳🇱',
    color: '#40C4FF',
    personality: {
      aggression: 0.35,
      paranoia: 0.40,
      greed: 0.55,
      honor: 0.60,
      cunning: 0.65,
      bravery: 0.40,
      diplomacy: 0.75,
      expansionism: 0.30,
      nationalism: 0.45,
    },
    military: { army: 100, air: 90, navy: 100, tech: 0.75 },
    economy: 400,
    population: 1700,
  },
  belgium: {
    name: 'Belgium',
    flag: '🇧🇪',
    color: '#AEEA00',
    personality: {
      aggression: 0.25,
      paranoia: 0.35,
      greed: 0.30,
      honor: 0.55,
      cunning: 0.50,
      bravery: 0.35,
      diplomacy: 0.80,
      expansionism: 0.20,
      nationalism: 0.40,
    },
    military: { army: 80, air: 60, navy: 40, tech: 0.65 },
    economy: 300,
    population: 1100,
  },
  switzerland: {
    name: 'Switzerland',
    flag: '🇨🇭',
    color: '#CCFF90',
    personality: {
      aggression: 0.15,
      paranoia: 0.30,
      greed: 0.40,
      honor: 0.80,
      cunning: 0.55,
      bravery: 0.50,
      diplomacy: 0.85,
      expansionism: 0.10,
      nationalism: 0.60,
    },
    military: { army: 150, air: 60, navy: 0, tech: 0.80 },
    economy: 400,
    population: 860,
  },
  austria: {
    name: 'Austria',
    flag: '🇦🇹',
    color: '#00C853',
    personality: {
      aggression: 0.35,
      paranoia: 0.45,
      greed: 0.35,
      honor: 0.60,
      cunning: 0.50,
      bravery: 0.45,
      diplomacy: 0.70,
      expansionism: 0.30,
      nationalism: 0.55,
    },
    military: { army: 80, air: 50, navy: 0, tech: 0.70 },
    economy: 300,
    population: 900,
  },
  poland: {
    name: 'Poland',
    flag: '🇵🇱',
    color: '#64DD17',
    personality: {
      aggression: 0.55,
      paranoia: 0.75,
      greed: 0.40,
      honor: 0.70,
      cunning: 0.50,
      bravery: 0.75,
      diplomacy: 0.45,
      expansionism: 0.45,
      nationalism: 0.85,
    },
    military: { army: 200, air: 120, navy: 40, tech: 0.60 },
    economy: 450,
    population: 3800,
  },
  czech: {
    name: 'Czech Republic',
    flag: '🇨🇿',
    color: '#82B1FF',
    personality: {
      aggression: 0.30,
      paranoia: 0.50,
      greed: 0.30,
      honor: 0.55,
      cunning: 0.50,
      bravery: 0.40,
      diplomacy: 0.65,
      expansionism: 0.20,
      nationalism: 0.55,
    },
    military: { army: 80, air: 50, navy: 0, tech: 0.70 },
    economy: 300,
    population: 1070,
  },
  hungary: {
    name: 'Hungary',
    flag: '🇭🇺',
    color: '#F50057',
    personality: {
      aggression: 0.50,
      paranoia: 0.60,
      greed: 0.40,
      honor: 0.55,
      cunning: 0.55,
      bravery: 0.55,
      diplomacy: 0.50,
      expansionism: 0.50,
      nationalism: 0.75,
    },
    military: { army: 100, air: 60, navy: 0, tech: 0.55 },
    economy: 250,
    population: 970,
  },
  romania: {
    name: 'Romania',
    flag: '🇷🇴',
    color: '#FFFF00',
    personality: {
      aggression: 0.45,
      paranoia: 0.60,
      greed: 0.40,
      honor: 0.55,
      cunning: 0.50,
      bravery: 0.55,
      diplomacy: 0.50,
      expansionism: 0.45,
      nationalism: 0.75,
    },
    military: { army: 120, air: 70, navy: 40, tech: 0.50 },
    economy: 300,
    population: 1900,
  },
  greece: {
    name: 'Greece',
    flag: '🇬🇷',
    color: '#EEFF41',
    personality: {
      aggression: 0.45,
      paranoia: 0.65,
      greed: 0.35,
      honor: 0.65,
      cunning: 0.55,
      bravery: 0.50,
      diplomacy: 0.55,
      expansionism: 0.40,
      nationalism: 0.80,
    },
    military: { army: 120, air: 80, navy: 90, tech: 0.55 },
    economy: 280,
    population: 1040,
  },
  bulgaria: {
    name: 'Bulgaria',
    flag: '🇧🇬',
    color: '#C51162',
    personality: {
      aggression: 0.40,
      paranoia: 0.55,
      greed: 0.35,
      honor: 0.55,
      cunning: 0.50,
      bravery: 0.50,
      diplomacy: 0.55,
      expansionism: 0.40,
      nationalism: 0.70,
    },
    military: { army: 80, air: 50, navy: 30, tech: 0.45 },
    economy: 200,
    population: 700,
  },
  serbia: {
    name: 'Serbia',
    flag: '🇷🇸',
    color: '#00E676',
    personality: {
      aggression: 0.60,
      paranoia: 0.75,
      greed: 0.40,
      honor: 0.65,
      cunning: 0.55,
      bravery: 0.70,
      diplomacy: 0.35,
      expansionism: 0.55,
      nationalism: 0.90,
    },
    military: { army: 100, air: 60, navy: 0, tech: 0.40 },
    economy: 180,
    population: 690,
  },
  sweden: {
    name: 'Sweden',
    flag: '🇸🇪',
    color: '#18FFFF',
    personality: {
      aggression: 0.25,
      paranoia: 0.30,
      greed: 0.30,
      honor: 0.75,
      cunning: 0.50,
      bravery: 0.40,
      diplomacy: 0.80,
      expansionism: 0.15,
      nationalism: 0.45,
    },
    military: { army: 80, air: 100, navy: 80, tech: 0.80 },
    economy: 350,
    population: 1030,
  },
  norway: {
    name: 'Norway',
    flag: '🇳🇴',
    color: '#FF4081',
    personality: {
      aggression: 0.30,
      paranoia: 0.35,
      greed: 0.30,
      honor: 0.70,
      cunning: 0.45,
      bravery: 0.45,
      diplomacy: 0.70,
      expansionism: 0.20,
      nationalism: 0.50,
    },
    military: { army: 60, air: 70, navy: 90, tech: 0.75 },
    economy: 300,
    population: 540,
  },
  finland: {
    name: 'Finland',
    flag: '🇫🇮',
    color: '#C6FF00',
    personality: {
      aggression: 0.35,
      paranoia: 0.55,
      greed: 0.25,
      honor: 0.75,
      cunning: 0.55,
      bravery: 0.65,
      diplomacy: 0.60,
      expansionism: 0.20,
      nationalism: 0.65,
    },
    military: { army: 60, air: 50, navy: 40, tech: 0.70 },
    economy: 250,
    population: 550,
  },
  denmark: {
    name: 'Denmark',
    flag: '🇩🇰',
    color: '#B2FF59',
    personality: {
      aggression: 0.30,
      paranoia: 0.30,
      greed: 0.30,
      honor: 0.65,
      cunning: 0.50,
      bravery: 0.40,
      diplomacy: 0.75,
      expansionism: 0.20,
      nationalism: 0.45,
    },
    military: { army: 50, air: 50, navy: 70, tech: 0.70 },
    economy: 250,
    population: 580,
  },
  ireland: {
    name: 'Ireland',
    flag: '🇮🇪',
    color: '#FFAB40',
    personality: {
      aggression: 0.25,
      paranoia: 0.35,
      greed: 0.25,
      honor: 0.70,
      cunning: 0.50,
      bravery: 0.45,
      diplomacy: 0.70,
      expansionism: 0.15,
      nationalism: 0.60,
    },
    military: { army: 40, air: 30, navy: 20, tech: 0.60 },
    economy: 250,
    population: 500,
  },
  russia: {
    name: 'Russia',
    flag: '🇷🇺',
    color: '#00B0FF',
    personality: {
      aggression: 0.85,
      paranoia: 0.90,
      greed: 0.80,
      honor: 0.35,
      cunning: 0.80,
      bravery: 0.80,
      diplomacy: 0.25,
      expansionism: 0.90,
      nationalism: 0.95,
    },
    military: { army: 800, air: 400, navy: 300, tech: 0.70 },
    economy: 1200,
    population: 14400,
  },
  ukraine: {
    name: 'Ukraine',
    flag: '🇺🇦',
    color: '#EA80FC',
    personality: {
      aggression: 0.55,
      paranoia: 0.80,
      greed: 0.30,
      honor: 0.75,
      cunning: 0.55,
      bravery: 0.85,
      diplomacy: 0.55,
      expansionism: 0.35,
      nationalism: 0.90,
    },
    military: { army: 250, air: 120, navy: 40, tech: 0.50 },
    economy: 400,
    population: 4100,
  },
  belarus: {
    name: 'Belarus',
    flag: '🇧🇾',
    color: '#F44336',
    personality: {
      aggression: 0.40,
      paranoia: 0.70,
      greed: 0.35,
      honor: 0.40,
      cunning: 0.60,
      bravery: 0.45,
      diplomacy: 0.40,
      expansionism: 0.30,
      nationalism: 0.65,
    },
    military: { army: 80, air: 40, navy: 0, tech: 0.40 },
    economy: 180,
    population: 940,
  },
  turkey: {
    name: 'Turkey',
    flag: '🇹🇷',
    color: '#00ACC1',
    personality: {
      aggression: 0.65,
      paranoia: 0.70,
      greed: 0.55,
      honor: 0.60,
      cunning: 0.65,
      bravery: 0.70,
      diplomacy: 0.50,
      expansionism: 0.60,
      nationalism: 0.85,
    },
    military: { army: 350, air: 200, navy: 150, tech: 0.60 },
    economy: 600,
    population: 8400,
  },
  lithuania: {
    name: 'Lithuania',
    flag: '🇱🇹',
    color: '#A7FFEB',
    personality: {
      aggression: 0.35,
      paranoia: 0.65,
      greed: 0.25,
      honor: 0.60,
      cunning: 0.45,
      bravery: 0.50,
      diplomacy: 0.55,
      expansionism: 0.25,
      nationalism: 0.75,
    },
    military: { army: 40, air: 20, navy: 10, tech: 0.45 },
    economy: 120,
    population: 280,
  },
  latvia: {
    name: 'Latvia',
    flag: '🇱🇻',
    color: '#76FF03',
    personality: {
      aggression: 0.30,
      paranoia: 0.60,
      greed: 0.25,
      honor: 0.55,
      cunning: 0.45,
      bravery: 0.45,
      diplomacy: 0.55,
      expansionism: 0.20,
      nationalism: 0.70,
    },
    military: { army: 30, air: 15, navy: 10, tech: 0.45 },
    economy: 100,
    population: 190,
  },
  estonia: {
    name: 'Estonia',
    flag: '🇪🇪',
    color: '#FF80AB',
    personality: {
      aggression: 0.30,
      paranoia: 0.60,
      greed: 0.25,
      honor: 0.60,
      cunning: 0.50,
      bravery: 0.45,
      diplomacy: 0.60,
      expansionism: 0.20,
      nationalism: 0.70,
    },
    military: { army: 20, air: 10, navy: 10, tech: 0.55 },
    economy: 90,
    population: 130,
  },
  croatia: {
    name: 'Croatia',
    flag: '🇭🇷',
    color: '#FFD600',
    personality: {
      aggression: 0.45,
      paranoia: 0.60,
      greed: 0.30,
      honor: 0.60,
      cunning: 0.50,
      bravery: 0.55,
      diplomacy: 0.55,
      expansionism: 0.35,
      nationalism: 0.80,
    },
    military: { army: 60, air: 30, navy: 20, tech: 0.45 },
    economy: 150,
    population: 410,
  },
  slovakia: {
    name: 'Slovakia',
    flag: '🇸🇰',
    color: '#FFC400',
    personality: {
      aggression: 0.30,
      paranoia: 0.50,
      greed: 0.30,
      honor: 0.55,
      cunning: 0.45,
      bravery: 0.40,
      diplomacy: 0.60,
      expansionism: 0.25,
      nationalism: 0.60,
    },
    military: { army: 40, air: 20, navy: 0, tech: 0.50 },
    economy: 150,
    population: 550,
  },
  slovenia: {
    name: 'Slovenia',
    flag: '🇸🇮',
    color: '#448AFF',
    personality: {
      aggression: 0.25,
      paranoia: 0.40,
      greed: 0.25,
      honor: 0.60,
      cunning: 0.45,
      bravery: 0.35,
      diplomacy: 0.65,
      expansionism: 0.15,
      nationalism: 0.55,
    },
    military: { army: 20, air: 10, navy: 0, tech: 0.55 },
    economy: 100,
    population: 210,
  },
  bosnia: {
    name: 'Bosnia',
    flag: '🇧🇦',
    color: '#7C4DFF',
    personality: {
      aggression: 0.40,
      paranoia: 0.65,
      greed: 0.30,
      honor: 0.45,
      cunning: 0.50,
      bravery: 0.50,
      diplomacy: 0.40,
      expansionism: 0.35,
      nationalism: 0.80,
    },
    military: { army: 40, air: 15, navy: 0, tech: 0.30 },
    economy: 80,
    population: 350,
  },
  moldova: {
    name: 'Moldova',
    flag: '🇲🇩',
    color: '#00BFA5',
    personality: {
      aggression: 0.30,
      paranoia: 0.60,
      greed: 0.25,
      honor: 0.50,
      cunning: 0.45,
      bravery: 0.35,
      diplomacy: 0.50,
      expansionism: 0.20,
      nationalism: 0.65,
    },
    military: { army: 20, air: 10, navy: 0, tech: 0.30 },
    economy: 60,
    population: 260,
  },
  luxembourg: {
    name: 'Luxembourg',
    flag: '🇱🇺',
    color: '#B388FF',
    personality: {
      aggression: 0.10,
      paranoia: 0.25,
      greed: 0.35,
      honor: 0.60,
      cunning: 0.45,
      bravery: 0.25,
      diplomacy: 0.85,
      expansionism: 0.05,
      nationalism: 0.40,
    },
    military: { army: 5, air: 2, navy: 0, tech: 0.70 },
    economy: 80,
    population: 63,
  },
  albania: {
    name: 'Albania',
    flag: '🇦🇱',
    color: '#D500F9',
    personality: {
      aggression: 0.50,
      paranoia: 0.65,
      greed: 0.30,
      honor: 0.60,
      cunning: 0.55,
      bravery: 0.60,
      diplomacy: 0.40,
      expansionism: 0.40,
      nationalism: 0.85,
    },
    military: { army: 30, air: 10, navy: 10, tech: 0.30 },
    economy: 60,
    population: 290,
  },
  north_macedonia: {
    name: 'North Macedonia',
    flag: '🇲🇰',
    color: '#2979FF',
    personality: {
      aggression: 0.35,
      paranoia: 0.55,
      greed: 0.25,
      honor: 0.55,
      cunning: 0.45,
      bravery: 0.45,
      diplomacy: 0.50,
      expansionism: 0.25,
      nationalism: 0.70,
    },
    military: { army: 20, air: 10, navy: 0, tech: 0.30 },
    economy: 40,
    population: 210,
  },
  montenegro: {
    name: 'Montenegro',
    flag: '🇲🇪',
    color: '#FF9100',
    personality: {
      aggression: 0.35,
      paranoia: 0.50,
      greed: 0.25,
      honor: 0.55,
      cunning: 0.45,
      bravery: 0.50,
      diplomacy: 0.50,
      expansionism: 0.25,
      nationalism: 0.70,
    },
    military: { army: 10, air: 5, navy: 5, tech: 0.30 },
    economy: 30,
    population: 62,
  },
};

const { DOCTRINE_ASSIGNMENTS } = require('./doctrines');

const EMOTION_TYPES = ['joy', 'anger', 'sadness', 'fear', 'surprise', 'disgust', 'hatred', 'love', 'pride', 'shame'];

class Faction {
  constructor(id, config) {
    this.id = id;
    this.name = config.name;
    this.flag = config.flag;
    this.color = config.color;
    this.personality = { ...config.personality };
    this.military = { ...config.military };
    this.economy = config.economy;
    this.population = config.population;
    this.alive = true;
    this.regions = [];
    this.relations = {};
    this.emotions = {};
    this.memory = [];
    this.lastWill = '';
    this.doctrineId = DOCTRINE_ASSIGNMENTS[id] || 'european';
    this.notificationQueue = [];
    this.chatHistory = [];
    this.lastNotificationCheck = Date.now();
    this.lastChatTime = Date.now();
    this.busy = false;
    this.currentAction = 'idle';
    this.actionProgress = 0;
    this._pendingChatQuote = null;
  }

  getTotalMilitaryPower() {
    return this.military.army * 1.0 + this.military.air * 0.8 + this.military.navy * 0.6;
  }

  getDisplayStatus() {
    return {
      id: this.id,
      name: this.name,
      flag: this.flag,
      color: this.color,
      army: this.military.army,
      air: this.military.air,
      navy: this.military.navy,
      economy: this.economy,
      population: this.population,
      alive: this.alive,
      regionCount: this.regions.length,
      totalPower: Math.round(this.getTotalMilitaryPower()),
      personality: this.personality,
      doctrineId: this.doctrineId,
      unreadNotifications: this.notificationQueue.filter(n => !n.read).length,
      currentAction: this.currentAction,
    };
  }
}

function createFactions() {
  const factions = {};
  for (const [id, config] of Object.entries(FACTIONS_CONFIG)) {
    factions[id] = new Faction(id, config);
  }

  for (const f1 of Object.values(factions)) {
    for (const f2 of Object.values(factions)) {
      if (f1.id !== f2.id) {
        const baseTrust = 0.3 + Math.random() * 0.4;
        f1.relations[f2.id] = { trust: baseTrust, opinion: Math.random() * 100, alliance: false, war: false, traded: 0 };
        f1.emotions[f2.id] = {
          dominant: 'neutral',
          joy: 0, anger: 0, sadness: 0, fear: 0,
          surprise: 0, disgust: 0, hatred: 0, love: 0,
          pride: 0, shame: 0,
        };
      }
    }
  }

  return factions;
}

module.exports = { createFactions, Faction, FACTIONS_CONFIG };
